module.exports.keys = {
  NOAA_WEATHER_API_KEY: process.env.NOAA_WEATHER_API_KEY,
  DARK_SKY_WEATHER_API_KEY: process.env.DARK_SKY_WEATHER_API_KEY,
  OPEN_WEATHER_API_KEY: process.env.OPEN_WEATHER_API_KEY

};
